language: php
php:
  # - 5.4
   - 5.5
   - 5.6
   - 7.0

sudo: false

cache:
   directories:
       - "$HOME/.composer/cache"
       - "$HOME/.php-cs-fixer"

before_script:
   - mkdir -p "$HOME/.php-cs-fixer"
   - composer update

script:
   #1.9 - vendor/bin/php-cs-fixer fix --cache-file "$HOME/.php-cs-fixer/.php_cs.cache" --dry-run --diff --verbose
   - vendor/bin/php-cs-fixer fix --dry-run --diff --verbose
   - php bin/Smoke.php -v
   - php bin/Smoke.php --num_urls=1 analyse http://www.amilio.de/thumb/61/3a/613aee53e10d7348f44ae6f47bff760b_180px.jpg -v
   - php bin/Smoke.php explain -v
   - php bin/Smoke.php warmup http://www.example.com/ -d1 -v
   - php bin/Smoke.php custom -cexample/custom.yml -v
   - phpunit --bootstrap vendor/autoload.php test/
